version: "3"

networks:
  nginx-php74-alpine:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "80:80"
    volumes:
    - ./code:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - nginx-php74-alpine

  php:
    image: php:7.4-fpm-alpine
    container_name: php74
    volumes:
    - ./code:/var/www
    ports:
    - "9000:9000"
    networks:
      - nginx-php74-alpine